[package]
name = "surrealism-cli"
version = "0.1.5"
description = "CLI for Surrealism"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license-file.workspace = true

[[bin]]
name = "surrealism"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
serde_json.workspace = true
surrealdb-core.workspace = true
surrealdb-types.workspace = true
surrealism-types = { workspace = true, features = ["host"] }
surrealism-runtime.workspace = true
tempfile.workspace = true
tokio.workspace = true
walrus.workspace = true
wasm-opt.workspace = true

[lints]
workspace = true
