edition = "2021"
hard_tabs = true
merge_derives = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Off"

# -----------------------------------
# Unstable options we would like to use in future
# -----------------------------------

#blank_lines_lower_bound = 1
#group_imports = "One"
#indent_style = "Block"
#match_arm_blocks = true
#reorder_impl_items = true
#wrap_comments = true
