[package]
name = "surrealism-types"
version = "0.1.0"
edition = "2021"
authors = ["Tobie Morgan Hitchcock <tobie@surrealdb.com>"]
description = "Types for Surrealism."
license = "BUSL-1.1"
repository = "https://github.com/surrealdb/surrealdb"
homepage = "https://github.com/surrealdb/surrealdb"

[features]
# Enable this feature for the host side (runtime) to make traits async
host = []

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
surrealdb-types.workspace = true
chrono.workspace = true
bytes = "1.10.1"
flatbuffers = "25.2.10"
rust_decimal = "1.37.2"

[lints]
workspace = true