[package]
name = "surrealism-types"
version = "0.1.2"
description = "Types for Surrealism"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license-file.workspace = true

[features]
# Enable this feature for the host side (runtime) to make traits async
host = []

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
surrealdb-types.workspace = true
chrono.workspace = true
bytes = "1.10.1"
flatbuffers = "25.2.10"
rust_decimal = "1.39.0"

[lints]
workspace = true
