[package]
name = "wasm-linker"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck.workspace = true
surrealml-llms.workspace = true
surrealml-tokenizers = { workspace = true, features = ["http-access"] }
wasmtime.workspace = true

[lints]
workspace = true
