[package]
name = "surrealml-core"
version = "0.1.9"
edition = "2021"
description = "The core machine learning library for SurrealML that enables SurrealDB to store and load ML models"
license-file = "LICENSE"

[features]
default = []
sklearn-tests = []
onnx-tests = []
torch-tests = []
tensorflow-tests = []
gpu = []
tokenizers = ["surrealml-tokenizers"]

[dependencies]
bytes = { workspace = true }
futures = { workspace = true }
hyper = "1.8.1"
ndarray = { workspace = true }
ort = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
surrealml-tokenizers = { path = "../tokenizers/", optional = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { version = "1.48.0", features = ["full"] }

[lib]
name = "surrealml_core"
path = "src/lib.rs"
