[package]
name = "surrealml-llms"
version = "0.1.0"
edition = "2024"
description = "An interface for loading and running models with candle transformers"
license = "LICENSE"

[dependencies]
candle-core.workspace = true
candle-nn.workspace = true
candle-transformers.workspace = true
hf-hub = { workspace = true, features = ["tokio"] }
serde = { workspace = true, features = ["derive"] }
surrealml-tokenizers = { workspace = true, features = ["http-access"] }
tempfile.workspace = true
thiserror.workspace = true

[lib]
name = "surrealml_llms"
path = "src/lib.rs"

[features]
http-access = []
local-gemma-test = []
