[package]
name = "surrealism-runtime"
version = "0.1.3"
description = "Runtime for Surrealism"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license-file.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
crossbeam-channel = "0.5"
reblessive = { workspace = true, features = ["tree"] }
serde.workspace = true
serde_json.workspace = true
surrealdb-types.workspace = true
thiserror.workspace = true
tokio.workspace = true
wasmtime.workspace = true
surrealism-types = { workspace = true, features = ["host"] }
tar.workspace = true
zstd.workspace = true
semver.workspace = true
wasmtime-wasi.workspace = true
toml.workspace = true
bytes = "1"
futures.workspace = true

[lints]
workspace = true