[package]
name = "c-wrapper"
version = "0.1.4"
edition = "2021"
description = "A Rust wrapper crate providing C bindings for SurrealML."
license-file = "LICENSE"

[dependencies]
base64.workspace = true
http-body-util = "0.1"
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["client", "client-legacy", "http1", "http2", "tokio"] }
ndarray.workspace = true
surrealml-core.workspace = true
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true, features = ["v4"] }

[lib]
crate-type = ["cdylib"]
